config/routes.rb
Rails.application.routes.draw do
  resources :drinks
  resources :ingredients

  root 'drinks#index'

end

app/models/drink.rb
class Drink < ActiveRecord::Base
  has_many :ingredients, through: :drink_ingredients
  has_many :drink_ingredients
end

app/models/drink_ingredient.rb
class DrinkIngredient < ActiveRecord::Base
  belongs_to :drink
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :drinks, through: :drink_ingredients
  has_many :drink_ingredients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
  before_action :set_drink, only: [:show, :edit, :update, :destroy]

  # GET /drinks
  # GET /drinks.json
  def index
    @drinks = Drink.all
  end

  # GET /drinks/1
  # GET /drinks/1.json
  def show
  end

  # GET /drinks/new
  def new
    @drink = Drink.new
  end

  # GET /drinks/1/edit
  def edit
  end

  # POST /drinks
  # POST /drinks.json
  def create
    @drink = Drink.new(drink_params)

    respond_to do |format|
      if @drink.save
        format.html { redirect_to @drink, notice: 'Drink was successfully created.' }
        format.json { render :show, status: :created, location: @drink }
      else
        format.html { render :new }
        format.json { render json: @drink.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drinks/1
  # PATCH/PUT /drinks/1.json
  def update
    respond_to do |format|
      if @drink.update(drink_params)
        format.html { redirect_to @drink, notice: 'Drink was successfully updated.' }
        format.json { render :show, status: :ok, location: @drink }
      else
        format.html { render :edit }
        format.json { render json: @drink.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drinks/1
  # DELETE /drinks/1.json
  def destroy
    @drink.destroy
    respond_to do |format|
      format.html { redirect_to drinks_url, notice: 'Drink was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_drink
      @drink = Drink.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def drink_params
      params.require(:drink).permit(:price, :name, :sell_price)
    end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  
  def index
    @ingredients = Ingredient.all
  end

  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  def show
    @ingredient = Ingredient.find(params[:id])
  end

  def destroy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/views/drinks/_form.html.erb
<%= form_for(@drink) do |f| %>
  <% if @drink.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@drink.errors.count, "error") %> prohibited this drink from being saved:</h2>

      <ul>
      <% @drink.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :sell_price %><br>
    <%= f.text_field :sell_price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/drinks/edit.html.erb
<h1>Editing Drink</h1>

<%= render 'form' %>

<%= link_to 'Show', @drink %> |
<%= link_to 'Back', drinks_path %>

app/views/drinks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Drinks</h1>

<table>
  <thead>
    <tr>
      <th>Price</th>
      <th>Name</th>
      <th>Sell price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @drinks.each do |drink| %>
      <tr>
        <td><%= drink.price %></td>
        <td><%= drink.name %></td>
        <td><%= drink.sell_price %></td>
        <td><%= link_to 'Show', drink %></td>
        <td><%= link_to 'Edit', edit_drink_path(drink) %></td>
        <td><%= link_to 'Destroy', drink, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Drink', new_drink_path %>

app/views/drinks/new.html.erb
<h1>New Drink</h1>

<%= render 'form' %>

<%= link_to 'Back', drinks_path %>

app/views/drinks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @drink.price %>
</p>

<p>
  <strong>Name:</strong>
  <%= @drink.name %>
</p>

<p>
  <strong>Sell price:</strong>
  <%= @drink.sell_price %>
</p>

<%= link_to 'Edit', edit_drink_path(@drink) %> |
<%= link_to 'Back', drinks_path %>

app/views/ingredients/_form.html.haml
= form_for(@ingredient) do |f|
  - if @ingredient.errors.any?
    #error_explanation
      %h2
        = pluralize(@ingredient.errors.count, "error")
        prohibited this ingredient from being saved:
      %ul
        - @ingredient.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br
      = f.text_field :name
  .field
    = f.label :spirit
    %br
      = f.text_field :spirit
  
  .actions
    = f.submit

app/views/ingredients/edit.html.haml
=render 'form'

app/views/ingredients/index.html.haml
%p#notice= notice
%h1 Listing ingredients
%table
  %thead
    %tr
      %th Price
      %th Name
      %th Sell price
      %th{:colspan => "3"}
  %tbody
    - @ingredients.each do |ingredient|
      %tr
        %td= ingredient.name
        %td= ingredient.spirit
        %td= link_to 'Show', ingredient
        %td= link_to 'Edit', edit_ingredient_path(ingredient)
        %td= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' }
%br
  = link_to 'New ingredient', new_ingredient_path

app/views/ingredients/show.html.haml
=render "form"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bartender</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>